[package]
name = "sha256_asm"
version = "0.1.0"
authors = ["kmolski <starfighter413@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
