[package]
name = "projekt-asm"
version = "0.1.0"
authors = ["kmolski <starfighter413@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
